name: 'Kubectl Helm AWS CLI Action'
description: 'A custom GitHub Action to use kubectl, helm, and AWS CLI in one package'
author: 'noose'
inputs:
  args:
    description: 'The command to run with kubectl, helm, and AWS CLI'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    KUBE_CONFIG_DATA: 'Cg==' # base64 encoded kubeconfig, or Cg== for empty
    AWS_ACCESS_KEY_ID: '' # can be populated from aws-actions/configure-aws-credentials
    AWS_SECRET_ACCESS_KEY: '' # can be populated from aws-actions/configure-aws-credentials
  args: |
    Your script
