# create a github pipeline to build container with kubectl, helm and aws cli v2 with different versions
# remember to use matrix strategy to build with different versions of kubectl and helm
on: [push]
jobs:
  build:
    strategy:
      matrix:
        kubectl_version: [1.31.0]
        helm_version: [3.14.0]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: noose/kubectl-helm-aws
        tags: ${{ matrix.kubectl_version }}-${{ matrix.helm_version }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          KUBECTL_VERSION=${{ matrix.kubectl_version }}
          HELM_VERSION=${{ matrix.helm_version }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
