on: [push]
jobs:
  build:
    strategy:
      matrix:
        kubectl_version: [1.31.0, 1.31.2]
        helm_version: [3.14.0, 3.16.3]
        aws_cli_version: [2.17.31, 2.21.0]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker.io
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: noose/kubectl-helm-aws
        tags: ${{ matrix.kubectl_version }}-${{ matrix.helm_version }}-${{ matrix.aws_cli_version }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          AWS_CLI_VERSION=${{ matrix.aws_cli_version }}
          KUBECTL_VERSION=${{ matrix.kubectl_version }}
          HELM_VERSION=${{ matrix.helm_version }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: docker.io/noose/kubectl-helm-aws
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
